// <auto-generated />
namespace LibrariDenisKoleci.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removedateofreturn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedateofreturn));
        
        string IMigrationMetadata.Id
        {
            get { return "202206061908086_removedateofreturn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
